#!/usr/bin/env python3
"""
img2c.py – Convert a PNG image to a C++ header containing a static BGRA pixel array.

Usage:
    python3 tools/img2c.py <input.png> <symbol_name> [<width> <height>]
        > kernel/gfx/assets/<symbol_name>.hpp

    If width/height are omitted the image is NOT resized.
    Default resize: 48x48 (desktop icon size).

Example:
    python3 tools/img2c.py assets/shell.png       icon_shell       48 48 > kernel/gfx/assets/icon_shell.hpp
    python3 tools/img2c.py assets/editor.png      icon_editor      48 48 > kernel/gfx/assets/icon_editor.hpp
    python3 tools/img2c.py assets/controlpanel.png icon_controlpanel 48 48 > kernel/gfx/assets/icon_controlpanel.hpp
    python3 tools/img2c.py assets/wallpaper.png   wallpaper             > kernel/gfx/assets/wallpaper.hpp

GPU pixel format: B8G8R8X8 (little-endian uint32_t = 0x00RRGGBB with gfx::rgb()).
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("// ERROR: Pillow not installed. Run:  pip3 install Pillow", file=sys.stderr)
    sys.exit(1)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    src_path    = sys.argv[1]
    symbol_name = sys.argv[2]
    target_w    = int(sys.argv[3]) if len(sys.argv) > 3 else None
    target_h    = int(sys.argv[4]) if len(sys.argv) > 4 else None

    img = Image.open(src_path).convert("RGBA")
    if target_w and target_h:
        img = img.resize((target_w, target_h), Image.LANCZOS)

    width, height = img.size
    pixels = list(img.getdata())   # list of (R, G, B, A) tuples

    guard = f"ASSETS_{symbol_name.upper()}_HPP"
    ns    = "gfx::assets"

    print(f"// AUTO-GENERATED by tools/img2c.py from {Path(src_path).name}")
    print(f"// Do not edit – regenerate with: python3 tools/img2c.py {src_path} {symbol_name} {width} {height}")
    print(f"#pragma once")
    print(f"#include <stdint.h>")
    print()
    print(f"namespace gfx {{ namespace assets {{")
    print()
    print(f"static constexpr uint32_t {symbol_name}_W = {width}u;")
    print(f"static constexpr uint32_t {symbol_name}_H = {height}u;")
    print()
    print(f"// B8G8R8A8 pixel data – B in bits 0-7, G in bits 8-15, R in bits 16-23, A in bits 24-31.")
    print(f"// Use gfx::blit_alpha(symbol, bg_color, ...) to composite over a background.")
    print(f"static const uint32_t {symbol_name}[{width} * {height}] = {{")

    COLS = 8
    for i, (r, g, b, a) in enumerate(pixels):
        val = b | (g << 8) | (r << 16) | (a << 24)   # B8G8R8A8
        if i % COLS == 0:
            print("    ", end="")
        print(f"0x{val:08X}u", end="")
        if i < len(pixels) - 1:
            print(",", end=" " if (i % COLS) < (COLS - 1) else "\n")
    if len(pixels) % COLS != 0:
        print()

    print(f"}};")
    print()
    print(f"}} }} // namespace gfx::assets")


if __name__ == "__main__":
    main()
